"""Initial migration

Revision ID: dd73c4fe6eee
Revises: 
Create Date: 2026-03-14 14:17:31.527070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd73c4fe6eee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='updated time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码（加密存储）'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='user_gender_enum'), nullable=True, comment='性别'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='个人简介'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='updated time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_index('phone_UNIQUE', 'user', ['phone'], unique=False)
    op.create_index('username_UNIQUE', 'user', ['username'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='新闻ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='新闻标题'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='新闻简介'),
    sa.Column('content', sa.Text(), nullable=False, comment='新闻内容'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('author', sa.String(length=50), nullable=True, comment='作者'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='分类ID'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('publish_time', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['category_id'], ['news_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_news_category_idx', 'news', ['category_id'], unique=False)
    op.create_index('idx_publish_time', 'news', ['publish_time'], unique=False)
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='令牌ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='令牌值'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('fk_user_token_user_idx', 'user_token', ['user_id'], unique=False)
    op.create_index('token_UNIQUE', 'user_token', ['token'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='收藏ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='新闻ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='收藏时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'news_id', name='user_news_unique')
    )
    op.create_index('fk_favorite_news_idx', 'favorite', ['news_id'], unique=False)
    op.create_index('fk_favorite_user_idx', 'favorite', ['user_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='历史ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='新闻ID'),
    sa.Column('view_time', sa.DateTime(), nullable=False, comment='浏览时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_history_news_idx', 'history', ['news_id'], unique=False)
    op.create_index('fk_history_user_idx', 'history', ['user_id'], unique=False)
    op.create_index('idx_view_time', 'history', ['view_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_view_time', table_name='history')
    op.drop_index('fk_history_user_idx', table_name='history')
    op.drop_index('fk_history_news_idx', table_name='history')
    op.drop_table('history')
    op.drop_index('fk_favorite_user_idx', table_name='favorite')
    op.drop_index('fk_favorite_news_idx', table_name='favorite')
    op.drop_table('favorite')
    op.drop_index('token_UNIQUE', table_name='user_token')
    op.drop_index('fk_user_token_user_idx', table_name='user_token')
    op.drop_table('user_token')
    op.drop_index('idx_publish_time', table_name='news')
    op.drop_index('fk_news_category_idx', table_name='news')
    op.drop_table('news')
    op.drop_index('username_UNIQUE', table_name='user')
    op.drop_index('phone_UNIQUE', table_name='user')
    op.drop_table('user')
    op.drop_table('news_category')
    op.execute('DROP TYPE IF EXISTS user_gender_enum')
    # ### end Alembic commands ###
